services:
  telebot:
    image: prandyhub/telebot:latest
    restart: unless-stopped
    environment:
      - Telebot__Token='Token'
      - Telebot__Downloader__Proxy='socks5://user:pass@host:port'
      - Telebot__Downloader__Cookies=/cookies/cookies.txt
    volumes:
      - /cookies:/cookies